# Stage 1: Build the Node.js application
FROM node:16 as builder

WORKDIR /app

COPY package*.json /app

RUN npm install

COPY .  /app

# You can change this to match your web port if needed
EXPOSE 3000
CMD ["node", "index.js"]
