apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: v1
kind: Secret
metadata:
  name: creds
  namespace: database
type: Opaque
data:
  db-password: c2VjcmV0cGFzc3dvcmQxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drage
  namespace: database
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drage
  template:
    metadata:
      labels:
        app: drage
    spec:
      containers:
      - name: drage
        image: us-east1-docker.pkg.dev/exalted-kit/mongo-registry/nodejs:v4
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: WEBport
          value: "3000"
        - name: DBuser
          value: "drage"
        - name: DBhosts
          value: "mongodb-0.mongodb-headless.database"
        - name: DBpass
          value: "secretpassword123"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: drage
  namespace: database
spec:
  type: LoadBalancer 
  ports:
  - name: api
    protocol: TCP
    port: 80
    targetPort: http
  selector:
    app: drage
