apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
apiVersion: v1
kind: Secret
metadata:
  name: creds
  namespace: frontend
type: Opaque
data:
  db-password: c2VjcmV0cGFzc3dvcmQxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: us-east1-docker.pkg.dev/exalted-kit/mongo-registry/nodejs:v4
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: WEBport
          value: "3000"
        - name: DBuser
          value: "sami"
        - name: DBhosts
          value: "mongodb-0.mongodb-headless.database:27017"
        - name: DBpass
          valueFrom:
            secretKeyRef:
              name: creds
              key: db-password
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: frontend
spec:
  type: LoadBalancer 
  ports:
  - name: api
    protocol: TCP
    port: 80
    targetPort: http
  selector:
    app: nodejs
