apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: us-east1-docker.pkg.dev/exalted-kit/mongo-registry/nodejs:v11
        ports:
        - name: http
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: staging
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 4000
    targetPort: http
  selector:
    app: node